project_id = "ohhgmoivhgkdxakrrutg"

[functions.daily-course-summary]
verify_jwt = false

[functions.whatsapp-scheduler]
verify_jwt = false

[functions.crm-mql]
verify_jwt = true

[functions.crm-agenda]
verify_jwt = true

[functions.future-student-lookup]
verify_jwt = false

[functions.complete-course-from-survey]
verify_jwt = false

[functions.meeting-reminder]
verify_jwt = false
