// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhyuwmrwhnyxyyztzvqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloeXV3bXJ3aG55eHl5enR6dnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMTgxMTksImV4cCI6MjA4Nzc5NDExOX0.qb_2jNDqKxG6B2CgFK1wZXKKDgGnrFeLwbbbZzRCYks";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'sb-metrics-auth-token',
  }
});

// BYPASS DE GETUSER NO LOCALHOST
const isLocalhost = typeof window !== "undefined" && (window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1");
if (isLocalhost) {
  supabase.auth.getUser = async () => {
    return {
      data: {
        user: {
          id: "bf0471c6-0152-460e-ae22-e7f3ec3969c4",
          email: "digitalavante3@gmail.com",
          role: "authenticated",
          aud: "authenticated",
          app_metadata: {},
          user_metadata: {},
          created_at: new Date().toISOString()
        } as any
      },
      error: null
    };
  };
}