// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhyuwmrwhnyxyyztzvqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloeXV3bXJ3aG55eHl5enR6dnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMTgxMTksImV4cCI6MjA4Nzc5NDExOX0.qb_2jNDqKxG6B2CgFK1wZXKKDgGnrFeLwbbbZzRCYks";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'sb-metrics-auth-token', // Chave de armazenamento dedicada para evitar colisão de login
  }
});